// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.56.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function ok(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: data
  };
}
function fail(message) {
  return {
    content: [{ type: "text", text: message }],
    isError: true
  };
}
function unauthenticated() {
  return fail("Not authenticated. Connect your BARBER-HUB account first.");
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my BARBER-HUB profile",
  description: "Return the signed-in user's BARBER-HUB profile: username, display name, country, roles (fan/barber), Barber Bucks balance, and barber profile details when they are a barber.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [profileRes, rolesRes, barberRes] = await Promise.all([
      supabase.from("profiles").select(
        "username, display_name, avatar_url, bio, country_code, user_type, barber_bucks, creator_level, is_creator, created_at"
      ).eq("user_id", userId).maybeSingle(),
      supabase.from("user_roles").select("role").eq("user_id", userId),
      supabase.from("barber_profiles").select(
        "id, name, nickname, specialty, bio, rating, years_experience, location, country_code, is_live, xp_total, xp_level, active_subscription_tier, competition_categories"
      ).eq("user_id", userId).maybeSingle()
    ]);
    if (profileRes.error) return fail(profileRes.error.message);
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail() ?? null,
      profile: profileRes.data ?? null,
      roles: (rolesRes.data ?? []).map((r) => r.role),
      barber_profile: barberRes.data ?? null
    };
    return ok(payload);
  }
});

// src/lib/mcp/tools/search-barbers.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var search_barbers_default = defineTool2({
  name: "search_barbers",
  title: "Search barbers",
  description: "Search the BARBER-HUB barber directory by name, nickname, specialty, city or country. Returns public barber profile details including rating, experience, location and live status.",
  inputSchema: {
    query: z.string().trim().max(120).optional().describe("Free-text match against barber name, nickname or specialty."),
    country_code: z.string().trim().length(2).optional().describe("ISO-2 country code filter, e.g. US."),
    live_only: z.boolean().optional().describe("Only return barbers currently live streaming."),
    limit: z.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("barber_profiles").select(
      "id, user_id, name, nickname, specialty, bio, rating, years_experience, location, shop_city, country_code, is_live, xp_level, competition_categories"
    ).order("rating", { ascending: false, nullsFirst: false }).limit(input.limit ?? 10);
    if (input.query) {
      const term = `%${input.query.replace(/[%,]/g, "")}%`;
      q = q.or(
        `name.ilike.${term},nickname.ilike.${term},specialty.ilike.${term}`
      );
    }
    if (input.country_code) {
      q = q.eq("country_code", input.country_code.toUpperCase());
    }
    if (input.live_only) q = q.eq("is_live", true);
    const { data, error } = await q;
    if (error) return fail(error.message);
    return ok({ count: data?.length ?? 0, barbers: data ?? [] });
  }
});

// src/lib/mcp/tools/list-battles.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_battles_default = defineTool3({
  name: "list_battles",
  title: "List battles",
  description: "List BARBER-HUB battles with their status, category, prize pool and schedule. Use status to narrow to live, upcoming, voting or completed battles.",
  inputSchema: {
    status: z2.string().trim().max(30).optional().describe("Filter by battle status, e.g. live, upcoming, voting, completed."),
    category: z2.string().trim().max(60).optional().describe("Filter by battle category."),
    limit: z2.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("battles").select(
      "id, title, description, category, status, prize_amount, currency, starts_at, created_at, barber1_id, barber2_id"
    ).order("created_at", { ascending: false }).limit(input.limit ?? 10);
    if (input.status) q = q.eq("status", input.status);
    if (input.category) q = q.eq("category", input.category);
    const { data, error } = await q;
    if (error) return fail(error.message);
    return ok({ count: data?.length ?? 0, battles: data ?? [] });
  }
});

// src/lib/mcp/tools/list-open-challenges.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_open_challenges_default = defineTool4({
  name: "list_open_challenges",
  title: "List open challenges",
  description: "List BARBER-HUB open challenges \u2014 barber-vs-barber callouts with Barber Bucks stakes, pot totals and acceptance status.",
  inputSchema: {
    status: z3.string().trim().max(30).optional().describe("Filter by challenge status, e.g. open, accepted, completed."),
    limit: z3.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("open_challenges").select(
      "id, title, status, challenger_username, accepted_by_username, stake_amount, pot_total, bounty_amount, duration_minutes, match_mode, created_at, expires_at, battle_id"
    ).order("created_at", { ascending: false }).limit(input.limit ?? 10);
    if (input.status) q = q.eq("status", input.status);
    const { data, error } = await q;
    if (error) return fail(error.message);
    return ok({ count: data?.length ?? 0, challenges: data ?? [] });
  }
});

// src/lib/mcp/tools/list-my-notifications.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_my_notifications_default = defineTool5({
  name: "list_my_notifications",
  title: "List my notifications",
  description: "List the signed-in user's BARBER-HUB notifications, newest first. Optionally return only unread ones.",
  inputSchema: {
    unread_only: z4.boolean().optional().describe("Only return unread notifications."),
    limit: z4.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let q = supabaseForUser(ctx).from("notifications").select("id, type, title, message, data, read, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(input.limit ?? 20);
    if (input.unread_only) q = q.eq("read", false);
    const { data, error } = await q;
    if (error) return fail(error.message);
    return ok({ count: data?.length ?? 0, notifications: data ?? [] });
  }
});

// src/lib/mcp/tools/mark-notifications-read.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var mark_notifications_read_default = defineTool6({
  name: "mark_notifications_read",
  title: "Mark notifications read",
  description: "Mark one or more of the signed-in user's BARBER-HUB notifications as read.",
  inputSchema: {
    notification_ids: z5.array(z5.string().uuid()).min(1).max(50).describe("IDs of notifications to mark as read.")
  },
  annotations: {
    readOnlyHint: false,
    destructiveHint: false,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("notifications").update({ read: true }).eq("user_id", ctx.getUserId()).in("id", input.notification_ids).select("id");
    if (error) return fail(error.message);
    return ok({ updated: data?.length ?? 0, ids: (data ?? []).map((r) => r.id) });
  }
});

// src/lib/mcp/index.ts
var projectRef = "msuepyfssovvkjzpfjzu";
var mcp_default = defineMcp({
  name: "barberhub-mcp",
  title: "BARBER-HUB",
  version: "0.1.0",
  instructions: "Tools for BARBER-HUB, a global barber competition platform. Callers act as their own signed-in BARBER-HUB user. Use `get_my_profile` for the user's identity, role (fan or barber) and Barber Bucks balance; `search_barbers` for the barber directory; `list_battles` and `list_open_challenges` for competition activity; and the notification tools to read and clear their inbox. All amounts are in Barber Bucks (BB), where $1 = 5 BB.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_my_profile_default,
    search_barbers_default,
    list_battles_default,
    list_open_challenges_default,
    list_my_notifications_default,
    mark_notifications_read_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
