// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msuepyfssovvkjzpfjzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zdWVweWZzc292dmtqenBmanp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjE1NDMsImV4cCI6MjA3MTg5NzU0M30.G5w88G7NxqUCX5hrafzg0VgwYd-MVYJh-DTeoVDQRiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});